### ISSUE TITLE
Can't make the USB installer boot.

### ISSUE THREAD

**Issue by mattcm747** [juniorcaesar/OC-A315-56-327T#1]
Hello, first of all thanks for putting all the effort into filling up and manually configuring the EFI file.
I had some problems trying to boot my usb drive stick to install MacOS with your EFI folder.
I am trying to install Big Sur.
When using other pre-compiled EFIs (easy to find on GitHub, specifically made for our same device) I can get to the OpenCore boot menu easily enough, though functions are broken.
I wanted to try your pre-compiled EFI folder because it looked well-cured, however after placing it into my USB drive and booting it from the BIOS, it just "ignores" it and jumps straight into Windows.
Thanks in advance for your help.

**Comment by mattcm747** [comment]
Nevermind, setting _showpicker = true_ and _HideAuxiliary = false_ seems to have fixed the problem.

**Comment by juniorcaesar** [comment]
i was thinking about this for a long time actually, i will also add verbose-boot enabled builds from now on so it would be easier to see the problems. 

EDIT: i enabled boot menu & added the DEBUG version of this EFI folder, you can check it out from the releases tab. thank you for your feedback!
